[package]
name = "raytracer"
version = "0.1.0"
authors = ["Piotr Doan <doanpiotr@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
png = "0.15.1"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.42"
typetag = "0.1.4"
