name: Rust
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build
    - name: Lint
      run: cargo clippy
    - name: Test
      run: cargo test
